// Home page — replace with your app's landing page or redirect
export default function Home() {
  return (
    <main style={{ padding: "2rem" }}>
      <h1>App</h1>
      <p>Generated by the Agentic Delivery Platform.</p>
    </main>
  );
}
