// ── API entry point ────────────────────────────────────────────────────────────
import Fastify from "fastify";
import cors from "@fastify/cors";
import swagger from "@fastify/swagger";
import swaggerUi from "@fastify/swagger-ui";
import pg from "pg";
import { env } from "./config/env.js";

// ── DB pool ───────────────────────────────────────────────────────────────────

const db = new pg.Pool({ connectionString: env.databaseUrl });

// ── Server ────────────────────────────────────────────────────────────────────

const app = Fastify({ logger: { level: env.logLevel } });

await app.register(cors, { origin: true });

if (env.nodeEnv !== "production") {
  await app.register(swagger, {
    openapi: {
      info: { title: "App API", version: "1.0.0" },
    },
  });
  await app.register(swaggerUi, { routePrefix: "/docs" });
}

// Expose db on app instance for use in route handlers
app.decorate("db", db);

// ── Health check ──────────────────────────────────────────────────────────────

app.get("/health", async () => ({
  status: "ok",
  timestamp: new Date().toISOString(),
}));

// ── Register feature routes ───────────────────────────────────────────────────
// Generated by the Build agent — import and register routes here.
// Example:
//   import { userRoutes } from "./routes/users.js";
//   await app.register(userRoutes, { prefix: "/api/users" });

// ── Start ─────────────────────────────────────────────────────────────────────

await app.listen({ port: env.port, host: "0.0.0.0" });
app.log.info(`API listening on port ${env.port}`);
